# Copyright (c) 2026 Alexandre Loeblein Heinen
#
# This project is licensed under the MIT License.
# See the LICENSE file for details.

title: "Alexandre Loeblein Heinen - Personal Website"
description: "Engineer, Math & Innovation Enthusiast, Conversationalist"
author: "Alexandre Loeblein Heinen"
url: "https://alexandrelheinen.github.io"

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-relative-links

# Relative links configuration
relative_links:
  enabled: true
  collections: false

# Kramdown configuration
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: false

# Social links
social:
  - name: LinkedIn
    url: https://www.linkedin.com/in/alexandrelheinen
    icon: linkedin
  - name: Malt
    url: https://www.malt.fr/profile/alexandreloebleinheinen
    icon: briefcase
  - name: GitHub
    url: https://github.com/alexandrelheinen
    icon: github
  - name: CV
    url: /files/cv.pdf
    icon: file-text
  - name: Blog
    url: /blog
    icon: rss